{{- if .Values.proxy.enabled -}}
{{- if .Values.proxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netbird.proxy.serviceAccountName" . }}
  labels:
    {{- include "netbird.proxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
